export const companyCard = [
  {
    id: 1,
    name: 'Clean ФЕЯ',
    description:
      'Профессиональная уборка офисов, уборка снега, полив и стрижка газона. Быстро, качественно и с гарантией чистоты.',
    services: [
      'Комплексное санитарное содержание офисов, коммерческих и производственных помещений – от 45 руб/м2',
      'Уборка офисов, коммерческих и производственных помещений генеральная, а также после строительства и ремонта от 200 руб/м2',
      'Санитарное содержание парковок и прилегающей территории в летний и зимний периоды (уборка текущая, уборка снега, полив и стрижка газона) – от 45 руб/м2',
    ],
    price: 5000,
    rating: 4.9,
    image: new URL('./assets/gil-ribeiro-3hO8igCybds-unsplash.jpg', import.meta.url).href,
    companyPhone: '+7 (495) 766-10-35',
  },
  {
    id: 2,
    name: 'WindowCare Masters',
    description: 'Специалисты по хрустальной чистоте окон и стеклянных конструкций',
    services: [
      'Мойка витражей высотных зданий',
      'Чистка оконных рам ПВХ',
      'Антидождевое покрытие для стекол',
      'Зимняя обработка против наледи',
    ],
    price: 7000,
    rating: 4.8,
    image: new URL('./assets/nuno-silva-Rcsa_Rg77Tc-unsplash.jpg', import.meta.url).href,
    companyPhone: '+7 (916) 447-88-32',
  },
  {
    id: 3,
    name: 'PostBuild Cleaners',
    description: 'Экспресс-уборка после строительных работ любой сложности',
    services: [
      'Удаление строительной пыли с вентиляции',
      'Полировка каменных поверхностей',
      'Химчистка мягкой мебели',
      'Утилизация строительного мусора',
    ],
    price: 6500,
    rating: 4.7,
    image: new URL('./assets/priscilla-du-preez-BuDD1HGco-4-unsplash.jpg', import.meta.url).href,
    companyPhone: '+7 (903) 669-12-57',
  },
  {
    id: 4,
    name: 'SmartOffice Care',
    description: 'Комплексное обслуживание бизнес-пространств 24/7',
    services: [
      'Ежедневная поддержка чистоты',
      'Заправка расходных материалов',
      'Умная система заказа расходников',
      'Мониторинг чистоты в реальном времени',
    ],
    price: 8000,
    rating: 4.6,
    image: new URL('./assets/towfiqu-barbhuiya--9gPKrsbGmc-unsplash.jpg', import.meta.url).href,
    companyPhone: '+7 (499) 322-01-99',
  },
]
